project_id = "elnarrbpsphoxgldzehh"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-domain.com"]
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = true
client_id = "1066291262307-8sgl29qov2dibhki15ao1aoscrgtne3n.apps.googleusercontent.com"
secret = "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"