// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elnarrbpsphoxgldzehh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbmFycmJwc3Bob3hnbGR6ZWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMDQ2MTcsImV4cCI6MjA3Njc4MDYxN30.RNofjJ6iBayE5vBpggRwF9N6PSRPmYLBbfRgEU4l_4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});